version: "3"
services:
  postgres-db:
    image: postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
  server:
    build: ./server
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    links:
      - postgres-db
  client:
    build: ./client
    env_file: .env
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
